# https://github.com/Sifan6688/Corne_zmk_oled

# OLED Display
CONFIG_ZMK_DISPLAY=y

# Enable eager debouncing
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=10

# Enable ZMK Studio for Realtime Keymap Updates
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# Uncomment the following line to enable USB Logging (this increases power usage by a significant amount, turn it off when not in use)
# CONFIG_ZMK_USB_LOGGING=y# Uncomment the following lines to enable the Corne RGB Underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y

# Uncomment the following line to enable the Corne OLED Display
# CONFIG_ZMK_DISPLAY=y

# Set deep sleep to 30 minutes
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000

# Make bluetooth stronger
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# OLED Display
CONFIG_ZMK_DISPLAY=y

# USB (y) or BT (n) preferred connection
CONFIG_ZMK_USB=n
# Turn on logging, and set ZMK logging to debug output
# CONFIG_ZMK_USB_LOGGING=n
CONFIG_CLOCK_CONTROL_NRF_K32SRC_250PPM=y
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

# Change board name
CONFIG_ZMK_KEYBOARD_NAME="Corne mini"

CONFIG_ZMK_COMBO_MAX_COMBOS_PER_KEY=20
CONFIG_ZMK_COMBO_MAX_COMBOS_PER_LAYER=20
